services:
  cqrs_app:
    image: cqrs_app
    container_name: cqrs_app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - cqrs_network
  
  cqrs_db:
    image: mysql:latest
    container_name: cqrs_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - cqrs_volumes:/var/lib/mysql
    networks:
      - cqrs_network
networks:
  cqrs_network:
volumes:
  cqrs_volumes: