// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"net/http"
	"test-cqrs/src/App/Controllers"
	"test-cqrs/src/App/Helpers"
	"test-cqrs/src/App/Repository/CommandRepository"
	"test-cqrs/src/App/Service/CommandService"
)

// Injectors from injector.go:

func InitServer() (*http.Server, func(), error) {
	db, cleanup, err := helpers.NewDb()
	if err != nil {
		return nil, nil, err
	}
	commandRepository := commandrepository.NewCommandRepositoryImpl()
	commandService := commandservice.NewCommandServiceImpl(db, commandRepository)
	controller := controllers.NewControllerImpl(commandService)
	router := NewRouter(controller)
	server := NewServer(router)
	return server, func() {
		cleanup()
	}, nil
}

// injector.go:

var NewSet = wire.NewSet(commandrepository.NewCommandRepositoryImpl, commandservice.NewCommandServiceImpl, controllers.NewControllerImpl, helpers.NewDb, NewRouter, wire.Bind(new(http.Handler), new(*httprouter.Router)), NewServer)
